<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>LanCast</RootNamespace>
    <AssemblyName>LanCast</AssemblyName>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <NoWarn>CS0618</NoWarn>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Version>1.2.1</Version>
    <Product>LanCast</Product>
    <Company>LanCast</Company>
  </PropertyGroup>
  <ItemGroup>
    <Using Remove="System.Windows.Forms" />
    <Using Remove="System.Drawing" />
    <Using Include="System.IO" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SIPSorcery" Version="6.0.11" />
    <PackageReference Include="Concentus" Version="2.2.2" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
  </ItemGroup>
  <ItemGroup>
    <Content Remove="wwwroot\**" />
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\app.png" />
    <Resource Include="Assets\Design\*.png" />
    <Resource Include="Assets\Fonts\*.ttf" />
    <Content Include="Assets\Fonts\LICENSE.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <EmbeddedResource Include="wwwroot\assets\*" LogicalName="assets/%(Filename)%(Extension)" />
    <EmbeddedResource Include="wwwroot\index.html" LogicalName="index.html" />
    <EmbeddedResource Include="..\..\tools\ffmpeg.exe.gz" LogicalName="ffmpeg.exe.gz" />
  </ItemGroup>
</Project>
